import type { AreaJuridica } from './types';

/**
 * Listas de documentos por tipo de processo: ponto de partida para o escritório adaptar.
 * Os itens marcados como opcionais não impedem o andamento; os demais são o mínimo para o ajuizamento ou a defesa.
 * São apoio técnico: o advogado responsável confere o que o caso concreto exige.
 */
export interface ChecklistPadrao { nome: string; tipo: string; area: AreaJuridica | null; descricao: string; itens: { nome: string; obrigatorio?: boolean }[] }
const o = (nome: string) => ({ nome, obrigatorio: false });
const r = (nome: string) => ({ nome });

const PESSOA = [r('Documento de identificação com foto (RG ou CNH)'), r('CPF'), r('Comprovante de residência atualizado (até 90 dias)')];
const FORMALIDADES = [r('Procuração assinada'), r('Contrato de honorários assinado'), r('Declaração de hipossuficiência (se for pedir gratuidade)'), o('Termo de consentimento LGPD assinado')];

export const CHECKLISTS_PADRAO: readonly ChecklistPadrao[] = [
  { nome: 'Reclamação trabalhista – empregado', tipo: 'Reclamação trabalhista', area: 'trabalhista', descricao: 'Documentos para ajuizar reclamação trabalhista (verbas rescisórias, horas extras, vínculo, etc.). Atenção à prescrição bienal/quinquenal (CF, art. 7º, XXIX).',
    itens: [...PESSOA, r('Carteira de Trabalho (CTPS) – todas as páginas, física ou digital'), r('Contrato de trabalho ou prova do vínculo'), r('Holerites / contracheques'), r('Termo de rescisão (TRCT) e guias de seguro-desemprego'), r('Extrato analítico do FGTS'), r('Extrato do CNIS'), o('Cartões de ponto ou registros de jornada'), o('Atestados médicos, CAT e laudos (se houver doença ou acidente)'), o('Mensagens, e-mails e áudios com a empresa'), o('Nome e contato de testemunhas'), o('Convenção ou acordo coletivo da categoria'), r('Data de admissão, de dispensa e último salário (anotar)'), ...FORMALIDADES] },
  { nome: 'Defesa trabalhista – empregador', tipo: 'Defesa trabalhista', area: 'trabalhista', descricao: 'Documentos para contestação do empregador em reclamação trabalhista. Reunir antes da audiência.',
    itens: [r('Notificação/citação e petição inicial recebidas'), r('Contrato social e cartão CNPJ'), r('Documento do preposto e carta de preposição'), r('Ficha de registro e contrato do empregado'), r('Recibos de pagamento assinados'), r('Cartões de ponto/controles de jornada'), r('Comprovantes de recolhimento de FGTS e INSS'), r('Termo de rescisão e comprovantes de pagamento'), r('Atestados, exames admissionais, periódicos e demissionais (ASO)'), o('PPRA/PGR, LTCAT, PCMSO e comprovantes de EPI'), o('Advertências, suspensões e demais documentos disciplinares'), o('Convenção ou acordo coletivo aplicável'), r('Procuração e carta de preposição assinadas'), r('Contrato de honorários assinado')] },
  { nome: 'Ação de indenização por danos morais e materiais', tipo: 'Ação de indenização', area: 'civel', descricao: 'Responsabilidade civil (CC, arts. 186, 927 e 944; CDC, quando houver relação de consumo).',
    itens: [...PESSOA, r('Documentos que comprovem o fato (contrato, nota fiscal, protocolo, boletim de ocorrência)'), r('Prova do dano (fotos, vídeos, laudos, orçamentos, prontuários)'), r('Comprovantes de despesas e prejuízos (recibos, notas)'), r('Comunicações com a parte contrária (mensagens, e-mails, protocolos de atendimento)'), r('Notificação extrajudicial enviada (se houver) e resposta'), o('Nome e contato de testemunhas'), o('Prints com data e hora; ata notarial, se for o caso'), o('Documentos de renda (para lucros cessantes)'), ...FORMALIDADES] },
  { nome: 'Ação de cobrança / execução de título', tipo: 'Cobrança e execução', area: 'civel', descricao: 'Cobrança de dívida ou execução de título extrajudicial (CPC, art. 784). O título original e o demonstrativo atualizado são essenciais.',
    itens: [...PESSOA, r('Título original (contrato, nota promissória, cheque, duplicata, confissão de dívida)'), r('Demonstrativo de débito atualizado (principal, correção, juros e multa)'), r('Comprovante de entrega do bem ou da prestação do serviço'), r('Notificações de cobrança e protesto'), o('Garantias (fiança, aval, hipoteca, alienação fiduciária)'), o('Pesquisa de bens do devedor'), r('Endereço atualizado da parte devedora'), ...FORMALIDADES] },
  { nome: 'Ação de consumidor (CDC)', tipo: 'Direito do consumidor', area: 'civel', descricao: 'Vício ou fato do produto/serviço, cobrança indevida, negativação e cancelamento (CDC, arts. 12 a 27 e 42).',
    itens: [...PESSOA, r('Nota fiscal, contrato ou comprovante da compra/contratação'), r('Protocolos de reclamação (SAC, Procon, consumidor.gov.br)'), r('Provas do defeito/falha (fotos, vídeos, laudo técnico)'), o('Extrato de negativação (Serasa, SPC) e cobranças indevidas'), r('Faturas e comprovantes de pagamento'), o('Anúncio, oferta ou propaganda'), o('Despesas decorrentes (conserto, transporte, aluguel)'), ...FORMALIDADES] },
  { nome: 'Ação de despejo / locação', tipo: 'Locação e despejo', area: 'civel', descricao: 'Lei 8.245/1991: despejo por falta de pagamento, denúncia vazia ou infração contratual.',
    itens: [...PESSOA, r('Contrato de locação assinado e aditivos'), r('Matrícula atualizada do imóvel'), r('Planilha de débito (aluguéis, encargos, IPTU, condomínio, multa)'), r('Notificação ao locatário e comprovante de entrega'), r('Garantia locatícia (fiador, caução, seguro-fiança) e documentos do garantidor'), o('Vistoria de entrada e saída'), o('Contas de consumo em aberto'), r('Endereço completo do locatário e do fiador'), ...FORMALIDADES] },
  { nome: 'Divórcio (consensual ou litigioso)', tipo: 'Divórcio', area: 'familia', descricao: 'EC 66/2010; CPC, arts. 731 a 734. Se houver filhos incapazes, o consensual exige via judicial.',
    itens: [...PESSOA, r('Certidão de casamento atualizada (até 90 dias)'), r('Certidão de nascimento dos filhos'), r('Documentos pessoais do cônjuge e comprovante de endereço'), r('Pacto antenupcial (se houver)'), r('Relação e comprovação dos bens (matrículas, CRLV, extratos, participações societárias)'), r('Comprovantes de renda dos cônjuges'), o('Dívidas comuns'), o('Proposta de guarda, convivência e alimentos'), o('Declaração de imposto de renda'), ...FORMALIDADES] },
  { nome: 'Alimentos / guarda e convivência', tipo: 'Alimentos e guarda', area: 'familia', descricao: 'Lei 5.478/1968; CC, arts. 1.694 e seguintes; ECA. Binômio necessidade × possibilidade.',
    itens: [...PESSOA, r('Certidão de nascimento do(a) filho(a)'), r('Documentos do(a) genitor(a) e endereço completo'), r('Comprovantes de renda de quem pede e do obrigado (se conhecido)'), r('Planilha das despesas da criança (escola, saúde, alimentação, moradia, transporte)'), o('Comprovantes de matrícula e boletins escolares'), o('Receitas e laudos médicos'), o('Prova de convivência/abandono (mensagens, testemunhas)'), o('Sentença ou acordo anterior'), ...FORMALIDADES] },
  { nome: 'Inventário e partilha', tipo: 'Inventário', area: 'familia', descricao: 'CPC, arts. 610 e seguintes (prazo de 2 meses para abertura – art. 611); extrajudicial possível quando todos são capazes e concordes (Res. CNJ 35/2007).',
    itens: [...PESSOA, r('Certidão de óbito'), r('Certidão de casamento/nascimento do falecido e do cônjuge'), r('Documentos pessoais de todos os herdeiros'), r('Certidões de nascimento ou casamento dos herdeiros'), r('Testamento (certidão negativa/positiva de testamento)'), r('Matrículas atualizadas dos imóveis e certidões de ônus'), r('CRLV dos veículos, extratos bancários e de investimentos, participações societárias'), r('Dívidas do espólio'), r('Certidões negativas fiscais (municipal, estadual, federal)'), r('Declaração de imposto de renda do falecido'), r('Comprovante do recolhimento do ITCMD'), ...FORMALIDADES] },
  { nome: 'Benefício previdenciário (aposentadoria / revisão)', tipo: 'Aposentadoria e benefícios INSS', area: 'previdenciario', descricao: 'Lei 8.213/1991 e EC 103/2019. Verificar regras de transição, tempo especial e prescrição quinquenal.',
    itens: [...PESSOA, r('CNIS atualizado'), r('Carteira de Trabalho (CTPS) – todas as páginas'), r('Carta de concessão/indeferimento e processo administrativo completo'), r('PPP, LTCAT e laudos (tempo especial)'), r('Contribuições como contribuinte individual/facultativo (guias)'), o('Certidão de tempo de contribuição de outros regimes'), o('Documentos de atividade rural (declarações, notas, bloco do produtor)'), o('Laudos e exames médicos (benefícios por incapacidade)'), r('Número do benefício (NB) e protocolo no Meu INSS'), ...FORMALIDADES] },
  { nome: 'BPC/LOAS e auxílio por incapacidade', tipo: 'Benefício por incapacidade / BPC', area: 'previdenciario', descricao: 'Lei 8.742/1993 (BPC) e Lei 8.213/1991 (auxílio por incapacidade). Prova médica e social é central.',
    itens: [...PESSOA, r('CadÚnico atualizado e NIS'), r('Comprovante de renda e composição do grupo familiar'), r('Laudos, exames e receitas médicas recentes (com CID e data)'), r('Atestados médicos e relatório do médico assistente'), r('Indeferimento administrativo e protocolo do pedido'), o('Fotos da residência e comprovantes de despesas'), o('CNIS e CTPS'), ...FORMALIDADES] },
  { nome: 'Abertura e alteração de empresa / contrato social', tipo: 'Societário', area: 'empresarial', descricao: 'Constituição, alteração contratual e dissolução (CC, arts. 997 e seguintes; Lei 14.195/2021).',
    itens: [r('Documentos pessoais dos sócios (RG, CPF, estado civil)'), r('Comprovante de residência dos sócios'), r('Definição do objeto social, CNAE, capital social e participação de cada sócio'), r('Endereço da sede e contrato de locação/IPTU'), r('Contrato social e alterações vigentes (se houver)'), o('Certidões negativas dos sócios'), o('Procuração para despachante/contador'), r('Procuração e contrato de honorários assinados')] },
  { nome: 'Recuperação de crédito empresarial / contratos', tipo: 'Contratos empresariais', area: 'empresarial', descricao: 'Análise e cobrança de obrigações empresariais.',
    itens: [r('Contrato social e cartão CNPJ do cliente'), r('Documentos do representante legal'), r('Contrato, aditivos e propostas comerciais'), r('Notas fiscais, duplicatas, boletos e comprovantes de entrega'), r('Notificações enviadas e respostas'), r('Planilha de débito atualizada'), o('Certidões da empresa devedora e pesquisa de bens'), r('Procuração e contrato de honorários assinados')] },
  { nome: 'Defesa em ação penal / inquérito', tipo: 'Defesa criminal', area: 'criminal', descricao: 'CPP e CF, art. 5º. Documentos para a defesa do acusado ou investigado. Prazos curtos: priorizar a citação (resposta à acusação em 10 dias – CPP, art. 396).',
    itens: [...PESSOA, r('Peças do inquérito/denúncia, citação e intimações recebidas'), r('Boletim de ocorrência e mandado/decisão (prisão, busca)'), r('Certidão de antecedentes criminais'), r('Comprovante de trabalho/renda e residência fixa'), o('Atestados de bons antecedentes, cartas e referências'), o('Documentos que comprovem álibi ou tese defensiva'), o('Laudos periciais e exames'), r('Nome e contato de testemunhas'), r('Procuração com poderes especiais (se for o caso) e contrato de honorários assinado')] },
  { nome: 'Mandado de segurança / ação contra a administração pública', tipo: 'Direito administrativo', area: 'administrativo', descricao: 'Lei 12.016/2009: prazo decadencial de 120 dias do ato (art. 23). Prova pré-constituída é indispensável.',
    itens: [...PESSOA, r('Ato impugnado (edital, decisão, notificação, auto de infração)'), r('Data de ciência do ato (para o prazo de 120 dias)'), r('Prova pré-constituída do direito líquido e certo'), r('Processo administrativo completo ou protocolos'), r('Identificação da autoridade coatora e do órgão'), o('Documentos de concurso/licitação (edital, classificação, recursos)'), ...FORMALIDADES] },
  { nome: 'Execução fiscal / defesa tributária', tipo: 'Tributário', area: 'tributario', descricao: 'Lei 6.830/1980: embargos em 30 dias da garantia; CTN. Verificar prescrição e decadência.',
    itens: [r('Contrato social e cartão CNPJ (ou documentos pessoais)'), r('Certidão de dívida ativa (CDA) e petição inicial'), r('Citação e comprovante da data'), r('Processo administrativo fiscal (auto de infração, defesa, decisão)'), r('Guias de pagamento, parcelamentos e comprovantes'), r('Escrituração fiscal e contábil do período'), o('Apólice de seguro-garantia ou carta de fiança'), o('Matrículas de bens para garantia'), r('Procuração e contrato de honorários assinados')] },
  { nome: 'Usucapião', tipo: 'Usucapião', area: 'civel', descricao: 'CC, arts. 1.238 e seguintes; CPC, art. 246, § 3º; extrajudicial no cartório (Lei 6.015/73, art. 216-A).',
    itens: [...PESSOA, r('Prova da posse mansa, pacífica e pelo tempo exigido (contas, IPTU, fotos, testemunhas)'), r('Planta e memorial descritivo assinados por engenheiro, com ART/RRT'), r('Matrícula ou certidão negativa do imóvel no Registro de Imóveis'), r('Certidões negativas de ações e tributos (IPTU/ITR)'), r('Nome e endereço dos confrontantes e do titular'), o('Contrato de compra e venda ou cessão de direitos'), o('Declaração de anuência dos confrontantes'), ...FORMALIDADES] },
  { nome: 'Acidente de trânsito / seguro (DPVAT e apólice)', tipo: 'Acidentes e seguros', area: 'civel', descricao: 'Responsabilidade civil, indenização e cobertura securitária. Prescrição ânua em seguros (CC, art. 206, § 1º, II) – verificar.',
    itens: [...PESSOA, r('Boletim de ocorrência'), r('CNH e CRLV (ou documento do veículo)'), r('Fotos, vídeos e laudo pericial do acidente'), r('Orçamentos e notas de conserto (3 orçamentos)'), r('Apólice e comunicação de sinistro; negativa da seguradora'), o('Laudos médicos, prontuários, receitas e comprovantes de gastos com tratamento'), o('Contato de testemunhas'), ...FORMALIDADES] },
  { nome: 'Documentos para atendimento inicial (qualificação)', tipo: 'Atendimento inicial', area: null, descricao: 'Lista básica de qualificação e formalização para qualquer caso novo.',
    itens: [...PESSOA, r('Estado civil, profissão, nacionalidade e endereço completo (anotar no cadastro)'), r('E-mail e telefone para contato'), r('Procuração assinada'), r('Contrato de honorários assinado'), o('Termo de consentimento LGPD assinado'), r('Documentos do caso reunidos pelo cliente'), r('Verificação de conflito de interesses e de prazos em curso')] },
  { nome: 'Documentos de pessoa jurídica (cliente empresarial)', tipo: 'Cliente pessoa jurídica', area: 'empresarial', descricao: 'Qualificação e poderes de representação de cliente empresa.',
    itens: [r('Cartão CNPJ atualizado'), r('Contrato social/estatuto e últimas alterações'), r('Documento e comprovante de residência do representante legal'), r('Ata de eleição da diretoria (se for S/A ou associação)'), r('Procuração assinada por quem tem poderes'), r('Contrato de honorários assinado'), o('Certidões negativas'), o('Termo de consentimento LGPD')] },
];
