-- GERADO por supabase/gerar_paridade.mjs (não edite): paridade SQL x TypeScript.
\set ON_ERROR_STOP on
select t.admin_db();
\echo == PAR1. _classificar contra os casos de referência
select t.ok((select diferenca = 0 and status = 'no_horario' from public._classificar('entrada', '08:00', 480, 5, 30)), 'classificar: entrada pontual');
select t.ok((select diferenca = -5 and status = 'no_horario' from public._classificar('entrada', '08:00', 475, 5, 30)), 'classificar: entrada 5 min antes (tolerância)');
select t.ok((select diferenca = 5 and status = 'no_horario' from public._classificar('entrada', '08:00', 485, 5, 30)), 'classificar: entrada 5 min depois (limite da tolerância)');
select t.ok((select diferenca = 6 and status = 'tolerancia' from public._classificar('entrada', '08:00', 486, 5, 30)), 'classificar: entrada 6 min depois');
select t.ok((select diferenca = 29 and status = 'tolerancia' from public._classificar('entrada', '08:00', 509, 5, 30)), 'classificar: entrada 29 min depois');
select t.ok((select diferenca = 30 and status = 'atraso' from public._classificar('entrada', '08:00', 510, 5, 30)), 'classificar: entrada 30 min depois = atraso');
select t.ok((select diferenca = 120 and status = 'atraso' from public._classificar('entrada', '08:00', 600, 5, 30)), 'classificar: entrada 2h depois = atraso');
select t.ok((select diferenca = -20 and status = 'tolerancia' from public._classificar('entrada', '08:00', 460, 5, 30)), 'classificar: entrada adiantada 20 min não é atraso');
select t.ok((select diferenca = 45 and status = 'atraso' from public._classificar('retorno_intervalo', '14:00', 885, 5, 30)), 'classificar: retorno do intervalo atrasado');
select t.ok((select diferenca = 3 and status = 'no_horario' from public._classificar('retorno_intervalo', '14:00', 843, 5, 30)), 'classificar: retorno do intervalo no horário');
select t.ok((select diferenca = -10 and status = 'tolerancia' from public._classificar('saida_intervalo', '12:00', 710, 5, 30)), 'classificar: saída para intervalo adiantada 10 min');
select t.ok((select diferenca = -30 and status = 'saida_antecipada' from public._classificar('saida_intervalo', '12:00', 690, 5, 30)), 'classificar: saída para intervalo 30 min antes = antecipada');
select t.ok((select diferenca = 0 and status = 'no_horario' from public._classificar('saida', '18:00', 1080, 5, 30)), 'classificar: saída no horário');
select t.ok((select diferenca = 3 and status = 'no_horario' from public._classificar('saida', '18:00', 1083, 5, 30)), 'classificar: saída 3 min depois');
select t.ok((select diferenca = 20 and status = 'extra' from public._classificar('saida', '18:00', 1100, 5, 30)), 'classificar: saída 20 min depois = extra');
select t.ok((select diferenca = 120 and status = 'extra' from public._classificar('saida', '18:00', 1200, 5, 30)), 'classificar: saída 2h depois = extra');
select t.ok((select diferenca = -15 and status = 'tolerancia' from public._classificar('saida', '18:00', 1065, 5, 30)), 'classificar: saída 15 min antes = tolerância');
select t.ok((select diferenca = -30 and status = 'saida_antecipada' from public._classificar('saida', '18:00', 1050, 5, 30)), 'classificar: saída 30 min antes = antecipada');
select t.ok((select diferenca = -180 and status = 'saida_antecipada' from public._classificar('saida', '18:00', 900, 5, 30)), 'classificar: saída 3h antes = antecipada');
select t.ok((select diferenca = 0 and status = 'extra' from public._classificar('entrada', null::text, 552, 5, 30)), 'classificar: sem horário previsto (dia de folga) = extra');
select t.ok((select diferenca = 0 and status = 'extra' from public._classificar('saida', null::text, 1020, 5, 30)), 'classificar: sem horário previsto na saída = extra');
select t.ok((select diferenca = 1 and status = 'tolerancia' from public._classificar('entrada', '08:00', 481, 0, 30)), 'classificar: tolerância zero: 1 min conta');
select t.ok((select diferenca = 15 and status = 'atraso' from public._classificar('entrada', '08:00', 495, 5, 15)), 'classificar: limite configurado em 15 min');
select t.ok((select diferenca = 45 and status = 'tolerancia' from public._classificar('entrada', '08:00', 525, 5, 60)), 'classificar: limite configurado em 60 min');
select t.ok((select diferenca = 40 and status = 'atraso' from public._classificar('entrada', '08:00', 520, 5, 30)), 'classificar: jornada contínua de estágio: entrada');
select t.ok((select diferenca = -40 and status = 'saida_antecipada' from public._classificar('saida', '14:00', 800, 5, 30)), 'classificar: jornada contínua de estágio: saída');
select t.ok((select diferenca = -2 and status = 'no_horario' from public._classificar('entrada', '08:00', 478, 5, 30)), 'classificar: virada de hora (07:58 para 08:00)');
select t.ok((select diferenca = 10 and status = 'tolerancia' from public._classificar('entrada', '00:00', 10, 5, 30)), 'classificar: madrugada (00:10 para 00:00)');
\echo == PAR2. _turno_previsto contra os casos de referência
select t.ok(public._turno_previsto('{"0":{"ativo":false,"entrada":"","saida_intervalo":"","retorno_intervalo":"","saida":""},"1":{"ativo":true,"entrada":"08:00","saida_intervalo":"12:00","retorno_intervalo":"14:00","saida":"18:00"},"2":{"ativo":true,"entrada":"08:00","saida_intervalo":"12:00","retorno_intervalo":"14:00","saida":"18:00"},"3":{"ativo":true,"entrada":"08:00","saida_intervalo":"12:00","retorno_intervalo":"14:00","saida":"18:00"},"4":{"ativo":true,"entrada":"08:00","saida_intervalo":"12:00","retorno_intervalo":"14:00","saida":"18:00"},"5":{"ativo":true,"entrada":"08:00","saida_intervalo":"12:00","retorno_intervalo":"14:00","saida":"18:00"},"6":{"ativo":true,"entrada":"08:00","saida_intervalo":"","retorno_intervalo":"","saida":"12:00"}}'::jsonb, 1, 'entrada') is not distinct from '08:00', 'turno: segunda: entrada');
select t.ok(public._turno_previsto('{"0":{"ativo":false,"entrada":"","saida_intervalo":"","retorno_intervalo":"","saida":""},"1":{"ativo":true,"entrada":"08:00","saida_intervalo":"12:00","retorno_intervalo":"14:00","saida":"18:00"},"2":{"ativo":true,"entrada":"08:00","saida_intervalo":"12:00","retorno_intervalo":"14:00","saida":"18:00"},"3":{"ativo":true,"entrada":"08:00","saida_intervalo":"12:00","retorno_intervalo":"14:00","saida":"18:00"},"4":{"ativo":true,"entrada":"08:00","saida_intervalo":"12:00","retorno_intervalo":"14:00","saida":"18:00"},"5":{"ativo":true,"entrada":"08:00","saida_intervalo":"12:00","retorno_intervalo":"14:00","saida":"18:00"},"6":{"ativo":true,"entrada":"08:00","saida_intervalo":"","retorno_intervalo":"","saida":"12:00"}}'::jsonb, 1, 'saida_intervalo') is not distinct from '12:00', 'turno: segunda: saída para intervalo');
select t.ok(public._turno_previsto('{"0":{"ativo":false,"entrada":"","saida_intervalo":"","retorno_intervalo":"","saida":""},"1":{"ativo":true,"entrada":"08:00","saida_intervalo":"12:00","retorno_intervalo":"14:00","saida":"18:00"},"2":{"ativo":true,"entrada":"08:00","saida_intervalo":"12:00","retorno_intervalo":"14:00","saida":"18:00"},"3":{"ativo":true,"entrada":"08:00","saida_intervalo":"12:00","retorno_intervalo":"14:00","saida":"18:00"},"4":{"ativo":true,"entrada":"08:00","saida_intervalo":"12:00","retorno_intervalo":"14:00","saida":"18:00"},"5":{"ativo":true,"entrada":"08:00","saida_intervalo":"12:00","retorno_intervalo":"14:00","saida":"18:00"},"6":{"ativo":true,"entrada":"08:00","saida_intervalo":"","retorno_intervalo":"","saida":"12:00"}}'::jsonb, 1, 'retorno_intervalo') is not distinct from '14:00', 'turno: segunda: retorno');
select t.ok(public._turno_previsto('{"0":{"ativo":false,"entrada":"","saida_intervalo":"","retorno_intervalo":"","saida":""},"1":{"ativo":true,"entrada":"08:00","saida_intervalo":"12:00","retorno_intervalo":"14:00","saida":"18:00"},"2":{"ativo":true,"entrada":"08:00","saida_intervalo":"12:00","retorno_intervalo":"14:00","saida":"18:00"},"3":{"ativo":true,"entrada":"08:00","saida_intervalo":"12:00","retorno_intervalo":"14:00","saida":"18:00"},"4":{"ativo":true,"entrada":"08:00","saida_intervalo":"12:00","retorno_intervalo":"14:00","saida":"18:00"},"5":{"ativo":true,"entrada":"08:00","saida_intervalo":"12:00","retorno_intervalo":"14:00","saida":"18:00"},"6":{"ativo":true,"entrada":"08:00","saida_intervalo":"","retorno_intervalo":"","saida":"12:00"}}'::jsonb, 1, 'saida') is not distinct from '18:00', 'turno: segunda: saída');
select t.ok(public._turno_previsto('{"0":{"ativo":false,"entrada":"","saida_intervalo":"","retorno_intervalo":"","saida":""},"1":{"ativo":true,"entrada":"08:00","saida_intervalo":"12:00","retorno_intervalo":"14:00","saida":"18:00"},"2":{"ativo":true,"entrada":"08:00","saida_intervalo":"12:00","retorno_intervalo":"14:00","saida":"18:00"},"3":{"ativo":true,"entrada":"08:00","saida_intervalo":"12:00","retorno_intervalo":"14:00","saida":"18:00"},"4":{"ativo":true,"entrada":"08:00","saida_intervalo":"12:00","retorno_intervalo":"14:00","saida":"18:00"},"5":{"ativo":true,"entrada":"08:00","saida_intervalo":"12:00","retorno_intervalo":"14:00","saida":"18:00"},"6":{"ativo":true,"entrada":"08:00","saida_intervalo":"","retorno_intervalo":"","saida":"12:00"}}'::jsonb, 6, 'entrada') is not distinct from '08:00', 'turno: sábado: entrada');
select t.ok(public._turno_previsto('{"0":{"ativo":false,"entrada":"","saida_intervalo":"","retorno_intervalo":"","saida":""},"1":{"ativo":true,"entrada":"08:00","saida_intervalo":"12:00","retorno_intervalo":"14:00","saida":"18:00"},"2":{"ativo":true,"entrada":"08:00","saida_intervalo":"12:00","retorno_intervalo":"14:00","saida":"18:00"},"3":{"ativo":true,"entrada":"08:00","saida_intervalo":"12:00","retorno_intervalo":"14:00","saida":"18:00"},"4":{"ativo":true,"entrada":"08:00","saida_intervalo":"12:00","retorno_intervalo":"14:00","saida":"18:00"},"5":{"ativo":true,"entrada":"08:00","saida_intervalo":"12:00","retorno_intervalo":"14:00","saida":"18:00"},"6":{"ativo":true,"entrada":"08:00","saida_intervalo":"","retorno_intervalo":"","saida":"12:00"}}'::jsonb, 6, 'saida_intervalo') is not distinct from null::text, 'turno: sábado: sem intervalo');
select t.ok(public._turno_previsto('{"0":{"ativo":false,"entrada":"","saida_intervalo":"","retorno_intervalo":"","saida":""},"1":{"ativo":true,"entrada":"08:00","saida_intervalo":"12:00","retorno_intervalo":"14:00","saida":"18:00"},"2":{"ativo":true,"entrada":"08:00","saida_intervalo":"12:00","retorno_intervalo":"14:00","saida":"18:00"},"3":{"ativo":true,"entrada":"08:00","saida_intervalo":"12:00","retorno_intervalo":"14:00","saida":"18:00"},"4":{"ativo":true,"entrada":"08:00","saida_intervalo":"12:00","retorno_intervalo":"14:00","saida":"18:00"},"5":{"ativo":true,"entrada":"08:00","saida_intervalo":"12:00","retorno_intervalo":"14:00","saida":"18:00"},"6":{"ativo":true,"entrada":"08:00","saida_intervalo":"","retorno_intervalo":"","saida":"12:00"}}'::jsonb, 6, 'saida') is not distinct from '12:00', 'turno: sábado: saída 12h');
select t.ok(public._turno_previsto('{"0":{"ativo":false,"entrada":"","saida_intervalo":"","retorno_intervalo":"","saida":""},"1":{"ativo":true,"entrada":"08:00","saida_intervalo":"12:00","retorno_intervalo":"14:00","saida":"18:00"},"2":{"ativo":true,"entrada":"08:00","saida_intervalo":"12:00","retorno_intervalo":"14:00","saida":"18:00"},"3":{"ativo":true,"entrada":"08:00","saida_intervalo":"12:00","retorno_intervalo":"14:00","saida":"18:00"},"4":{"ativo":true,"entrada":"08:00","saida_intervalo":"12:00","retorno_intervalo":"14:00","saida":"18:00"},"5":{"ativo":true,"entrada":"08:00","saida_intervalo":"12:00","retorno_intervalo":"14:00","saida":"18:00"},"6":{"ativo":true,"entrada":"08:00","saida_intervalo":"","retorno_intervalo":"","saida":"12:00"}}'::jsonb, 0, 'entrada') is not distinct from null::text, 'turno: domingo inativo');
select t.ok(public._turno_previsto('{"1":{"ativo":true,"entrada":"08:00","saida_intervalo":"","retorno_intervalo":"","saida":"14:00"}}'::jsonb, 3, 'entrada') is not distinct from null::text, 'turno: dia inexistente na escala');
select t.ok(public._turno_previsto('{"2":{"ativo":false,"entrada":"08:00","saida_intervalo":"","retorno_intervalo":"","saida":"14:00"}}'::jsonb, 2, 'entrada') is not distinct from null::text, 'turno: dia inativo mesmo com horários');
